### PR TITLE
Add `.gitattributes`, unify eol/encoding

### PR DESCRIPTION
**Pull request by Repiteo**
Implements a basic `.gitattributes` to further ensure `lf` as the repository encoding. Additionally touched a handful of files that weren't using `lf`/`utf8` as expected.

### CODE REVIEW

**Comment by raulsntos** [comment]
Thanks. Looks like Visual Studio may need the `.sln` file to use UTF-8 with BOM[^1]. Not sure if this also applies to the `.csproj` files, and I don't use Visual Studio. Otherwise, the changes look good to me.

**Comment by Repiteo** [comment]
Now that you mention it, `.csproj` and `.sln` are indeed likely exceptions. To play it safe, I'll set them both up with `crlf`/`utf-8-bom` & have `.gitattributes`/`.editorconfig` reflect that.

**Review by raulsntos — COMMENTED** [review]
Can you revert the GUID changes to `Godot.sln` (as discussed in https://github.com/godotengine/godot/pull/91479#discussion_r1589448927)? Then it should be good to merge, thanks!

**Comment by Repiteo** [comment]
Somehow missed that I never got that fix in, whoops. Well, better late than never!

**Comment by raulsntos** [comment]
It looks like the tests are failing on Windows because it expects CRLF endings in the generated `.cs` files for some reason. I don't know why changing the line endings in the `.csproj`/`.sln` would affect this though.

**Comment by Repiteo** [comment]
The easiest workaround I could find was ensuring the generated files use `\n` line endings.

**Comment by Repiteo** [comment]
I believe the default checkout behavior for Git on Windows has `autocrlf=true`, which would make all unspecified files have `\r\n` eol. Making them explicitly `lf` has the benefit of ensuring that `crlf` can't be passed to the repo itself, but it causes weird edge-cases on Windows for some Microsoft tools.

In any case, I applied the changes to the generator tests instead. Now after reading the files it converts the line endings to `System.Environment.NewLine`, effectively making them ignored when compared. There might be a more efficient way of pulling this off, but it got the job done.

**Comment by raulsntos** [comment]
> In any case, I applied the changes to the generator tests instead. Now after reading the files it converts the line endings to `System.Environment.NewLine`, effectively making them ignored when compared.

That seems like the recommended approach[^1] so it works for me :+1:

[^1]: https://github.com/dotnet/roslyn-sdk/issues/983#issuecomment-1130623676

**Review by raulsntos — APPROVED** [review]

**Comment by raulsntos** [comment]
Thanks!

**Pull request merged**
